name: .NET WPF CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: WpfApp1.sln           # Replace if your solution name differs
      Project_Path: WpfApp1.csproj         # Replace if your project file name differs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x              # Adjust version as needed

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build project
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish build
      run: dotnet publish ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --output ./publish

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: PublishedWpfApp
        path: ./publish
